stages:
  - build
  - deploy
  - push

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_COMMIT_BRANCH == "main"'

variables:
  JAVA_HOME: /Library/Java/JavaVirtualMachines/jdk-21.jdk/Contents/Home
  PATH: $JAVA_HOME/bin:/usr/local/bin:/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin

build:
  stage: build
  tags:
    - MacBook Pro
  before_script:
    - echo "--- 📦 Setup environment ---"
    - echo $JAVA_HOME
  script:
    - echo "---🔨Build immagine Docker ---"
    - ./mvnw clean package -DskipTests
    - docker build -t manage-orders-app:latest .
    - docker tag manage-orders-app:latest antoniobasileo/manage-orders-app:latest
    - docker push antoniobasileo/manage-orders-app:latest
    - echo "---✅ Immagine docker pushata su Docker Hub (antoniobasileo/manage-orders-app:latest) ---"

deploy:
  stage: deploy
  tags:
    - MacBook Pro
  script:
    - echo "-- 🏗️️ Deploy su Kubernetes ---"
    - kubectl config use-context docker-desktop
    - cd /Users/antoniobasileo/progetti/kube-config
    - ./scripts/apply.sh manage-orders general
    - echo "---✅ Deploy completato su Kubernetes ---"
    - cd /Users/antoniobasileo/progetti/manage-orders
    - git remote add github git@github.com:AntonioBasileo/manage-orders.git
    - git add .
    - git commit -m "ci - auto-commit after successful deploy [skip ci]"
    - git push github $CI_COMMIT_BRANCH || echo "⚠️ Nessuna modifica da pushare su GitHub"
    - echo "---✅ Push su GitHub completato ---"
